[package]
name = "ratatui-image"
version = "0.1.0"
edition = "2021"
autoexamples = true
authors = ["Benjamin Große <ste3ls@gmail.com>"]
description = "An image widget for ratatui, supporting sixels"
keywords = ["ratatui", "image", "sixel", "tui", "terminal"]
repository = "https://github.com/benjajaja/ratatui-image"
readme = "README.md"
license = "MIT"
exclude = [
  "assets/*",
  ".github",
  "Makefile.toml",
  "CONTRIBUTING.md",
  "*.log",
  "tags",
]
rust-version = "1.65.0"

[features]
default = ["crossterm"]
# demo = ["dep:crossterm", "dep:termion", "dep:termwiz"]
crossterm = ["dep:crossterm"]
termion = ["dep:termion"]
termwiz = ["dep:termwiz"]

[dependencies]
dyn-clone = "1.0.11"
crossterm = { git = "https://github.com/benjajaja/crossterm", rev = "db515a16f95b36b4871488aa543f564bc929d62e" , optional = true }
hanbun = { git = "https://github.com/benjajaja/hanbun", rev = "12c1656fb1f46acdcf08fdc2eaa8003f954319ab" } # "0.4.1"
image = { version = "0.24.5" }
ratatui = { git = "https://github.com/benjajaja/ratatui", rev = "8729b61fab885dc141c6e0968b4863386c544d9d", features = ["crossterm", "termion", "termwiz" ] }
sixel-rs = { version = "0.3.3" }
termion = { version = "2.0", optional = true }
termwiz = { version = "0.20", optional = true }

[[example]]
name = "demo"
# XXX this runs for all of the terminal backends, so it can't be built using --all-features or scraped
doc-scrape-examples = true
