[env]
BACKEND = "crossterm"
[env.termion]
BACKEND = "termion"
[env.termwiz]
BACKEND = "termwiz"

[tasks.default]
alias = "ci"

[tasks.ci-all]
script = '''
cargo make ci
cargo make --profile termion ci
cargo make --profile termwiz ci
'''

[tasks.ci]
dependencies = [
  "fmt",
  "clippy",
  "check",
  "test",
  "readme",
]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--tests", "--all-features", "--", "-D", "warnings"]

[tasks.check]
command = "cargo"
args = ["check", "--all-features", "--all-targets"]

[tasks.test]
command = "cargo"
args = ["test", "--all-features", "--all-targets"]

[tasks.readme]
command = "cargo"
args = ["readme", "-o", "README.md"]

[tasks.run-example]
command = "cargo"
args = [
  "run", 
  "--release", 
  "--example", 
  "demo",
  "--features", "sixel,rustix,serde,crossterm",
]

# screenshot instructions for xmonad / tiling WMs:
# 1. cargo make screenshot-spawn-xterm
# 2. Float the new xterm window
# 3. In xterm: cargo make screenshot-capture
# 3b. If the resize caused a black screen, run last step again.

[tasks.screenshot]
dependencies = [
  "screenshot-build",
  "screenshot-capture-in-xterm",
  "screenshot-diff",
]

[tasks.screenshot-build]
command = "cargo"
args = [
  "build",
  "--example",
  "screenshot",
  "--features", "sixel,rustix,crossterm",
]

[tasks.screenshot-run]
command = "cargo"
args = [
  "run",
  "--example",
  "screenshot",
  "--features", "sixel,rustix,crossterm",
  "--", "--wait",
]

[tasks.demo-build]
command = "cargo"
args = [
  "build",
  "--example",
  "demo",
  "--features", "sixel,rustix,crossterm",
]


[tasks.screenshot-capture-in-xterm]
command = "cargo"
args = [
  "make",
  "screenshot-spawn-xterm",
  "-e", "cargo make screenshot-capture",
]

[tasks.screenshot-spawn-xterm]
command = "xterm"
args = [
  "-ti", "340",
  "-fa", "DejaVu",
  "-fs", "7",
  "-bg", "black",
  "-fg", "white",
  "${@}"
]

[tasks.screenshot-capture]
dependencies = [
  "screenshot-build",
]
command = "menyoki"
args = [
  "--quiet",
  "capture",
  "--countdown", "1",
  # "--size", "200x300", # does not work with xmonad
  # "--font", "-*-dejavu sans-*-*-*-*-7-*-*-*-*-*-*-*", # has no effect with xmonad
  "./target/debug/examples/screenshot",
  "png",
  "save",
  "target/screenshot.png",
]

[tasks.screenshot-record]
dependencies = [
  "demo-build",
]
command = "menyoki"
args = [
  "--quiet",
  "record",
  # "--countdown", "1",
  # "--size", "200x300", # does not work with xmonad
  # "--font", "-*-dejavu sans-*-*-*-*-7-*-*-*-*-*-*-*", # has no effect with xmonad
  "./target/debug/examples/demo",
  "gif",
  "save",
  "target/recording.gif",
]

[tasks.screenshot-diff]
command = "dify"
args = [
  "-t", "0.15",
  "assets/test_screenshot.png",
  "target/screenshot.png",
  "-o", "target/diff.png",
]

[tasks.xterm-stderr]
script = '''
cargo make screenshot-spawn-xterm -e "cargo run --example demo --features sixel,rustix,crossterm 2>$(tty)"
'''

[tasks.xvfb-screenshot]
dependencies = ["screenshot-build"]
run_task = [
  {name = ["xvfb", "xvfb-xwd", "xvfb-kitty"], fork = true, parallel = true},
]

[tasks.xvfb]
script = '''
Xvfb :99 -screen 0 320x240x8 +extension GLX +render -terminate 1
'''

[tasks.xvfb-xterm]
dependencies = ["screenshot-build"]
env = { "DISPLAY" = ":99" }
script = '''
until xterm -e true; do
  sleep 0.1
done
xterm -ti 340 -bg black -fg white -e "cargo make screenshot-run"
'''

[tasks.xvfb-kitty]
dependencies = ["screenshot-build"]
env = { "DISPLAY" = ":99" }
script = '''
until xterm -e true; do
  sleep 0.1
done
kitty -o linux_display_server=x11 cargo make screenshot-run
'''


[tasks.xvfb-xwd]
env = { "DISPLAY" = ":99" }
script = '''
until stat ./target/SCREENSHOT_PID 1>/dev/null 2>&1; do
  sleep 0.1
done
PID=$(cat ./target/SCREENSHOT_PID)
if [ "$PID" == "" ]; then exit 1; fi
xwd -root -silent | convert xwd:- png:./target/xwd.png
rm ./target/SCREENSHOT_PID
kill $PID
'''
